language: ruby
sudo: false
rvm:
- 2.2.7
script:
- bundle exec rake test
deploy:
  provider: rubygems
  api_key:
    secure: "GKAY/pMWLxQrPfeHNRTsWzefs150e/pZzHeWgiv4j/+KUrvqsl/djasB+9ZqrR20bL5AJVQSpfri51czhuTVhieOAjxneUY2MAHhXr0VSDt8O6949HHtBmWqstDtGX3IL/hU5IpPnEhSQ7v+OMss895zcTqFVAK37bBY/5OXPqaqeUksWtnm6HT6DDX6ia0zYefIFoZvSR6WsgGwjlVTznm6ieNj2hwVL2Hil/DrldeC85SYEvc0uUKu4rcEcUxGIzqu1wm1RObLHHBgsY+qzXq5PkHdup0RDrmu97MMUjmZ1EIDUPVOmFrCIGk5As7qIcIK0F1ARaVxgiSFJ5M6h+b1viaMShDmoQFisAymhR8SrpYRKb05stu9cHx6Np4k00/81AgOmbcBzBonSNrEa2wsNvDPw+LT6a8c33Kiw7DD6SpWMH+R2ZlNObZF9RD8VxCK+YoqbLUjCdGuFou9cmKgBWUCTx3oVPWbu2sF2jo6XoldUr7ManqQUTHGiGhYOJmo8PHW6LyEoNs8AmoKdTWUF8lDdCQZ8nkiBlJWIl2W1tngljLZQtUpnJ6aKjZMTAzoqRvDe4M0MZ9WpstNsDF2F/1qwN94aOdTq3jgSdWFAzk9wrwiXXGONrXUpM1eL+KvYvUt9ePLuFS2Pdk5LwIA1Y1xj0YcLl0A8VUQi38="
  gem: rudash
  on:
    repo: Attrash-Islam/rudash
