language: ruby
sudo: false
rvm:
- 2.2.7
script:
- bundle exec rake test
deploy:
  provider: rubygems
  api_key:
    secure: M+3NCQ+trUYWvszxjEJ1nOX6KAgMqbVSA7G55rzOOqInGM1SjVxdAXNP+d3sJVpLsqeYBY9ObCnH/fw25g/9tMAgpgU2ntSnIWc4RT6oywQBxdosruxlzyCDebijE7djo+5Jjnlt7Ln15Hvg5m9/OY8msoKiflm/L/dBol/LY2cfIWShn+lP40NPXDD8iL0PFqSiwDeK5Z3SxES1pk3mgaiLHwKlKSrPuxqi32MfdTFexaaqYTbhZTsMOYibOSQcDIzDcP63vIJsWqiqLv9sZLTFk7M0thv+RrNLeaJhjlZGfaJkWVo6oPm3hMGF/u7BZrnWhfzAxUeEsTOOqIO8uGupRjUcGhV5U0Qxu5rCHT/CjVeRca9VY36OWgrmOLN7cWLqE4I4OF9TPSDjo1jZGTnEf+mYxxTjqNwsqM2ykhS9QDS+kxnZZeQGiOj39dGBJxv4ZouwvvFub9heeNBOq0Nl0fpW1pqItTccMBA27GTAb6nHO7rJU/5joRyOS5TXnysidqFUWQSNOU76pHhCKMh/YqGFlcvR0jjqmkgGfN8UYELuEz1VxbG7rM77fdpDjfoUMknj4UL5z0gEZo5LGbNrrJayR3X2UjeI1Au/vx/ndGVhPLIPb5Vg1EkjoBcK9D9g+dzsT6N9w1Y0KR9wLD+31MUWIy9h8Ou8WyjEDpk=
  gem: rudash
  on:
    tags: true
    repo: Attrash-Islam/rudash
